### PR TITLE
fixed misleading TL;DR related to #103

### PR DESCRIPTION
**Pull request by daknuett**
This is the IMO most intuitive way of showing how flake8-aaa looks like. However some examples might be helpful for beginners. On the other hand I think a link to the examples should be in the TL;DR instead, to keep it short.

### CODE REVIEW

**Comment by daknuett** [comment]
I added the link in the TL;DR.

**Comment by jamescooke** [comment]
Thanks for this @daknuett  

I was a bit stuck on good ways to express this better in the README and this does a much better job than anything I could come up with :+1:

**Comment by jamescooke** [comment]
@daknuett I've noticed that the commits you've made here are not associated with your Github account, which means that you don't appear on the contributors list here: https://github.com/jamescooke/flake8-aaa/graphs/contributors , plus your Github avatar does not appear on the commits above.

If you care about this / want the "Github points", then I think this could be to do with your email configuration as per: https://help.github.com/en/articles/why-are-my-contributions-not-showing-up-on-my-profile#you-havent-added-your-local-git-commit-email-to-your-profile

**Comment by daknuett** [comment]
@jamescooke thank you! I have been wondering since a while why my contributions never show up. Turns out I used the wrong email alias. Now everything should be working.

**Pull request merged**
